"""add ai_run_id and source_gap fields to video_outputs

Revision ID: 005c4b0383a9
Revises: 55eefb8eb88d
Create Date: 2026-08-24 21:56:26.664953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '005c4b0383a9'
down_revision: Union[str, Sequence[str], None] = '55eefb8eb88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_outputs', sa.Column('ai_run_id', sa.String(length=64), nullable=True, comment='AI 편집 실행(run) 식별자'))
    op.add_column('video_outputs', sa.Column('missing_scene_roles', sa.JSON(), nullable=True, comment='부족한 장면 역할 목록(SOURCE_GAP 전용)'))
    op.add_column('video_outputs', sa.Column('available_options', sa.JSON(), nullable=True, comment='선택 가능한 대응 옵션(SOURCE_GAP 전용)'))
    op.alter_column('video_outputs', 'render_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='상태(대기/처리중/완료/실패/소스부족)',
               existing_comment='상태(대기/처리중/완료/실패)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_outputs', 'render_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               comment='상태(대기/처리중/완료/실패)',
               existing_comment='상태(대기/처리중/완료/실패/소스부족)',
               existing_nullable=False)
    op.drop_column('video_outputs', 'available_options')
    op.drop_column('video_outputs', 'missing_scene_roles')
    op.drop_column('video_outputs', 'ai_run_id')
    # ### end Alembic commands ###
