"""add shortform_sessions table and editing template columns

Revision ID: 09e88d81b191
Revises: d404c43210b0
Create Date: 2026-08-24 19:46:26.726715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09e88d81b191'
down_revision: Union[str, Sequence[str], None] = 'd404c43210b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortform_sessions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='세션 ID'),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='가게 ID(작성자는 store_id -> stores.user_id로 도출)'),
    sa.Column('session_token', sa.String(length=64), nullable=False, comment='AI 세션 식별자'),
    sa.Column('status', sa.Enum('ACTIVE', 'ACCEPTED', 'DISCARDED', name='sessionstatus', native_enum=False, length=20), nullable=False, comment='세션 생명주기(진행중/수락됨/폐기됨)'),
    sa.Column('project_state', sa.JSON(), nullable=True, comment='최신 project_state 캐시(AI 응답 그대로)'),
    sa.Column('last_recommendation', sa.JSON(), nullable=True, comment='최신 recommendation 캐시(AI 응답 그대로)'),
    sa.Column('shown_template_ids', sa.JSON(), nullable=True, comment='지금까지 보여준 영상편집템플릿 ID 목록(AI 응답 캐시)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index(op.f('ix_shortform_sessions_store_id'), 'shortform_sessions', ['store_id'], unique=False)
    op.add_column('video_formats', sa.Column('editing_template_id', sa.String(length=64), nullable=True, comment='AI 서버의 영상편집템플릿 ID'))
    op.add_column('video_formats', sa.Column('editing_template_version', sa.Integer(), nullable=True, comment='영상편집템플릿 버전'))
    op.create_unique_constraint('uq_video_formats_template', 'video_formats', ['editing_template_id', 'editing_template_version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_video_formats_template', 'video_formats', type_='unique')
    op.drop_column('video_formats', 'editing_template_version')
    op.drop_column('video_formats', 'editing_template_id')
    op.drop_index(op.f('ix_shortform_sessions_store_id'), table_name='shortform_sessions')
    op.drop_table('shortform_sessions')
    # ### end Alembic commands ###
