"""create video_formats and link project fk

Revision ID: 132e7a3a4755
Revises: 8c3ae5754eaf
Create Date: 2026-08-23 13:56:17.298701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132e7a3a4755'
down_revision: Union[str, Sequence[str], None] = '8c3ae5754eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_formats',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='포맷 ID'),
    sa.Column('format_title', sa.String(length=200), nullable=False, comment='포맷명'),
    sa.Column('format_type', sa.String(length=20), nullable=True, comment='유형(밈/잔잔한 소개)'),
    sa.Column('reference_url', sa.String(length=255), nullable=False, comment='원본 참고 URL(원본 파일은 저장하지 않고 링크만 보관)'),
    sa.Column('source_platform', sa.String(length=50), nullable=True, comment='원본 플랫폼(임베드 방식 분기에 사용)'),
    sa.Column('expected_duration_sec', sa.Integer(), nullable=True, comment='예상 촬영/영상 시간(초)'),
    sa.Column('shooting_difficulty', sa.String(length=20), nullable=True, comment='촬영 난이도'),
    sa.Column('face_exposure_level', sa.String(length=20), nullable=True, comment='얼굴 노출 요구 수준'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_url')
    )
    op.create_index(op.f('ix_video_formats_face_exposure_level'), 'video_formats', ['face_exposure_level'], unique=False)
    op.create_index(op.f('ix_video_formats_format_type'), 'video_formats', ['format_type'], unique=False)
    op.create_foreign_key(None, 'store_shorts_projects', 'video_formats', ['video_format_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_shorts_projects', type_='foreignkey')
    op.drop_index(op.f('ix_video_formats_format_type'), table_name='video_formats')
    op.drop_index(op.f('ix_video_formats_face_exposure_level'), table_name='video_formats')
    op.drop_table('video_formats')
    # ### end Alembic commands ###
