"""create stores table

Revision ID: 23fd8fdf7f13
Revises: 9455a292d932
Create Date: 2026-08-23 11:37:04.066535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23fd8fdf7f13'
down_revision: Union[str, Sequence[str], None] = '9455a292d932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='가게 ID'),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='소유 사용자 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='상호명'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='업종'),
    sa.Column('sub_category', sa.String(length=100), nullable=True, comment='세부 업종'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='주소'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='위도'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='경도'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('business_hours', sa.String(length=500), nullable=True, comment='영업시간/휴무일'),
    sa.Column('brand_tone', sa.Text(), nullable=True, comment='브랜드 분위기/말투'),
    sa.Column('brand_color', sa.String(length=20), nullable=True, comment='브랜드 색상'),
    sa.Column('logo_url', sa.String(length=255), nullable=True, comment='로고 이미지 URL'),
    sa.Column('info_source', sa.String(length=50), nullable=True, comment='이 정보를 가져온 출처(NAVER/KAKAO/MANUAL 등)'),
    sa.Column('external_channel_url', sa.String(length=255), nullable=True, comment='네이버플레이스/배달앱 등 외부 채널 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_user_id'), 'stores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_user_id'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
