"""create sns tables and add publish_kit

Revision ID: 548fc558f4ae
Revises: 9cfa61663df4
Create Date: 2026-08-23 22:56:20.795332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548fc558f4ae'
down_revision: Union[str, Sequence[str], None] = '9cfa61663df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sns_connections',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='연동 ID'),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='사용자 ID'),
    sa.Column('sns_platform', sa.String(length=30), nullable=True, comment='연동 플랫폼(INSTAGRAM/YOUTUBE/NAVER/TIKTOK)'),
    sa.Column('sns_account_name', sa.String(length=100), nullable=True, comment='플랫폼상의 계정명(동일 플랫폼 복수 연동 시 구분용)'),
    sa.Column('access_token', sa.String(length=500), nullable=True, comment='게시물 연결·통계 조회 API 호출용 액세스 토큰'),
    sa.Column('refresh_token', sa.String(length=500), nullable=True, comment='리프레시 토큰'),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True, comment='토큰 만료일시(UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sns_connections_user_id'), 'sns_connections', ['user_id'], unique=False)
    op.create_table('sns_posts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='게시물 ID'),
    sa.Column('video_output_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='게시(공유)한 산출물 ID'),
    sa.Column('sns_connection_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='연결에 사용한 SNS 연동 계정 ID'),
    sa.Column('post_platform', sa.String(length=30), nullable=True, comment='게시 플랫폼'),
    sa.Column('external_post_id', sa.String(length=100), nullable=True, comment='플랫폼상의 실제 게시물 ID - 연결 확정 시점에 채워짐(성과 API 조회 키)'),
    sa.Column('post_caption', sa.Text(), nullable=True, comment='캡션/문구'),
    sa.Column('post_hashtags', sa.String(length=500), nullable=True, comment='해시태그'),
    sa.Column('post_status', sa.Enum('PENDING_LINK', 'LINKED', name='poststatus', native_enum=False, length=20), nullable=False, comment='상태(연결대기/연결완료)'),
    sa.Column('posted_at', sa.DateTime(), nullable=True, comment='게시일시(연결된 게시물의 실제 게시 시각, UTC)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='레코드 생성일시(공유 버튼을 누른 시각)'),
    sa.ForeignKeyConstraint(['sns_connection_id'], ['sns_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_output_id'], ['video_outputs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sns_posts_sns_connection_id'), 'sns_posts', ['sns_connection_id'], unique=False)
    op.create_index(op.f('ix_sns_posts_video_output_id'), 'sns_posts', ['video_output_id'], unique=False)
    op.add_column('store_shorts_projects', sa.Column('publish_kit', sa.JSON(), nullable=True, comment='게시자료(캡션/해시태그/post_note) - 15.1 AI 생성 결과'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shorts_projects', 'publish_kit')
    op.drop_index(op.f('ix_sns_posts_video_output_id'), table_name='sns_posts')
    op.drop_index(op.f('ix_sns_posts_sns_connection_id'), table_name='sns_posts')
    op.drop_table('sns_posts')
    op.drop_index(op.f('ix_sns_connections_user_id'), table_name='sns_connections')
    op.drop_table('sns_connections')
    # ### end Alembic commands ###
