"""create storyboard_scenes and shooting summary columns

Revision ID: 54f3cf0cc2e6
Revises: 7f6461565465
Create Date: 2026-08-23 17:43:29.136518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f3cf0cc2e6'
down_revision: Union[str, Sequence[str], None] = '7f6461565465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyboard_scenes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='장면 ID'),
    sa.Column('shorts_project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='숏폼 프로젝트 ID'),
    sa.Column('scene_order', sa.Integer(), nullable=False, comment='장면 순서'),
    sa.Column('scene_description', sa.Text(), nullable=True, comment='화면/행동/구도 설명'),
    sa.Column('scene_dialogue', sa.Text(), nullable=True, comment='대사 텍스트'),
    sa.Column('scene_subtitle', sa.Text(), nullable=True, comment='자막 텍스트'),
    sa.Column('shot_type', sa.String(length=50), nullable=True, comment='샷 유형(촬영 가이드 오버레이 선택에 사용)'),
    sa.Column('target_duration_sec', sa.Integer(), nullable=True, comment='목표 길이(초)'),
    sa.ForeignKeyConstraint(['shorts_project_id'], ['store_shorts_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storyboard_scenes_shorts_project_id'), 'storyboard_scenes', ['shorts_project_id'], unique=False)
    op.add_column('store_shorts_projects', sa.Column('estimated_shooting_sec', sa.Integer(), nullable=True, comment='예상 촬영 소요시간(초)'))
    op.add_column('store_shorts_projects', sa.Column('required_people', sa.Integer(), nullable=True, comment='필요 인원'))
    op.add_column('store_shorts_projects', sa.Column('props', sa.JSON(), nullable=True, comment='필요 소품 목록'))
    op.add_column('store_shorts_projects', sa.Column('shooting_difficulty', sa.String(length=20), nullable=True, comment='촬영 난이도'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shorts_projects', 'shooting_difficulty')
    op.drop_column('store_shorts_projects', 'props')
    op.drop_column('store_shorts_projects', 'required_people')
    op.drop_column('store_shorts_projects', 'estimated_shooting_sec')
    op.drop_index(op.f('ix_storyboard_scenes_shorts_project_id'), table_name='storyboard_scenes')
    op.drop_table('storyboard_scenes')
    # ### end Alembic commands ###
