"""add is_active to video_formats

Revision ID: 55eefb8eb88d
Revises: a840dd2f99ad
Create Date: 2026-08-24 21:27:29.622011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55eefb8eb88d'
down_revision: Union[str, Sequence[str], None] = 'a840dd2f99ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'video_formats',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
            comment='ACTIVE 여부 - false면 추천·피드 노출 대상 아님',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_formats', 'is_active')
    # ### end Alembic commands ###
