"""create push_tokens table

Revision ID: 59b5687bd2dc
Revises: c8d4e2f6a901
Create Date: 2026-08-26 17:41:26.738755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '59b5687bd2dc'
down_revision: Union[str, Sequence[str], None] = 'c8d4e2f6a901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='푸시 토큰 ID'),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='사용자 ID (사용자당 최신 토큰 하나만 유지)'),
    sa.Column('push_token', sa.String(length=255), nullable=False, comment='Expo Push Token'),
    sa.Column('platform', sa.Enum('IOS', 'ANDROID', name='pushplatform', native_enum=False, length=10), nullable=False, comment='IOS 또는 ANDROID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_tokens')
    # ### end Alembic commands ###
