"""make store_photos.has_sensitive_info nullable

Revision ID: 7692e0541164
Revises: caba912f8ced
Create Date: 2026-08-24 19:13:51.292120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7692e0541164'
down_revision: Union[str, Sequence[str], None] = 'caba912f8ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_photos', 'has_sensitive_info',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               comment="고객 얼굴 등 민감정보 포함 여부(편집 시 사용 제한 판단). AI 판별 전에는 null(미확인) — false로 채우면 '민감정보 없음'으로 오인될 수 있다(AI팀 지침, docs/AI_연동_입출력.md 27번)",
               existing_comment='고객 얼굴 등 민감정보 포함 여부(편집 시 사용 제한 판단)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_photos', 'has_sensitive_info',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               comment='고객 얼굴 등 민감정보 포함 여부(편집 시 사용 제한 판단)',
               existing_comment="고객 얼굴 등 민감정보 포함 여부(편집 시 사용 제한 판단). AI 판별 전에는 null(미확인) — false로 채우면 '민감정보 없음'으로 오인될 수 있다(AI팀 지침, docs/AI_연동_입출력.md 27번)")
    # ### end Alembic commands ###
