"""create format_favorites and make promotion_purpose nullable

Revision ID: 7f6461565465
Revises: 132e7a3a4755
Create Date: 2026-08-23 15:11:54.323825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7f6461565465'
down_revision: Union[str, Sequence[str], None] = '132e7a3a4755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('format_favorites',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='찜 ID'),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='찜한 사용자 ID'),
    sa.Column('video_format_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='찜한 포맷 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='찜한 일시(UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_format_id'], ['video_formats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_format_id', name='uq_format_favorites_user_format')
    )
    op.create_index(op.f('ix_format_favorites_user_id'), 'format_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_format_favorites_video_format_id'), 'format_favorites', ['video_format_id'], unique=False)
    op.alter_column('store_shorts_projects', 'promotion_purpose',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True,
               existing_comment='홍보 목적(메뉴소개/이벤트알리기/가게소개/고객늘리기)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('store_shorts_projects', 'promotion_purpose',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False,
               existing_comment='홍보 목적(메뉴소개/이벤트알리기/가게소개/고객늘리기)')
    op.drop_index(op.f('ix_format_favorites_video_format_id'), table_name='format_favorites')
    op.drop_index(op.f('ix_format_favorites_user_id'), table_name='format_favorites')
    op.drop_table('format_favorites')
    # ### end Alembic commands ###
