"""create store_shorts_projects table

Revision ID: 8c3ae5754eaf
Revises: dbd93a5b9f1d
Create Date: 2026-08-23 13:20:02.354327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3ae5754eaf'
down_revision: Union[str, Sequence[str], None] = 'dbd93a5b9f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_shorts_projects',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='숏폼 프로젝트 ID'),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='가게 ID(작성자는 store_id -> stores.user_id로 도출)'),
    sa.Column('video_format_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='선택한 포맷 ID'),
    sa.Column('store_target_customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='선택한 타깃 ID'),
    sa.Column('menu_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='홍보 목적이 메뉴소개일 때 선택한 메뉴 ID. 그 외 목적일 땐 NULL'),
    sa.Column('promotion_purpose', sa.String(length=50), nullable=False, comment='홍보 목적(메뉴소개/이벤트알리기/가게소개/고객늘리기)'),
    sa.Column('promotion_detail', sa.JSON(), nullable=True, comment='홍보 목적별 상세 데이터. promotion_purpose에 따라 구조가 다름'),
    sa.Column('face_exposure_mode', sa.String(length=20), nullable=True, comment='얼굴 노출 모드'),
    sa.Column('shooting_condition', sa.Text(), nullable=True, comment='촬영 조건(촬영자 유무, 가능 시간 등)'),
    sa.Column('shorts_status', sa.Enum('DRAFT', 'IN_PROGRESS', 'COMPLETED', name='shortsstatus', native_enum=False, length=20), nullable=False, comment='진행 상태(초안/진행중/완료)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.ForeignKeyConstraint(['menu_id'], ['store_menus.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_target_customer_id'], ['store_target_customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_shorts_projects_store_id'), 'store_shorts_projects', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_shorts_projects_store_id'), table_name='store_shorts_projects')
    op.drop_table('store_shorts_projects')
    # ### end Alembic commands ###
