"""create users table

Revision ID: 9455a292d932
Revises: 
Create Date: 2026-08-21 16:34:51.084145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9455a292d932'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='사용자 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='비밀번호 해시'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='이름/닉네임'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='계정 활성화 여부(TRUE=활성, FALSE=탈퇴) - 로그인 가능 여부 판단'),
    sa.Column('terms_agreed', sa.Boolean(), nullable=False, comment='이용약관/개인정보 필수 동의 여부'),
    sa.Column('marketing_agreed', sa.Boolean(), nullable=False, comment='마케팅 수신 선택 동의 여부'),
    sa.Column('agreed_at', sa.DateTime(), nullable=True, comment='약관 동의 시각(UTC)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
