"""create video_outputs table

Revision ID: 9cfa61663df4
Revises: bbb10d72276d
Create Date: 2026-08-23 22:19:09.571917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfa61663df4'
down_revision: Union[str, Sequence[str], None] = 'bbb10d72276d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_outputs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='산출물 ID'),
    sa.Column('shorts_project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='숏폼 프로젝트 ID'),
    sa.Column('edit_recipe', sa.Text(), nullable=True, comment='편집 레시피(JSON) - 이 산출물을 만든 편집 명령'),
    sa.Column('video_url', sa.String(length=255), nullable=True, comment='결과 영상 파일 URL'),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True, comment='커버 이미지 URL'),
    sa.Column('target_platform', sa.String(length=50), nullable=True, comment='대상 플랫폼/출력 규격'),
    sa.Column('resolution', sa.String(length=20), nullable=True, comment='해상도'),
    sa.Column('has_licensed_audio', sa.Boolean(), nullable=True, comment='상업 안전 음원 포함 여부'),
    sa.Column('render_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='renderstatus', native_enum=False, length=20), nullable=False, comment='상태(대기/처리중/완료/실패)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.ForeignKeyConstraint(['shorts_project_id'], ['store_shorts_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_outputs_shorts_project_id'), 'video_outputs', ['shorts_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_outputs_shorts_project_id'), table_name='video_outputs')
    op.drop_table('video_outputs')
    # ### end Alembic commands ###
