"""add insight_data to store_insights

Revision ID: a6a8e36cf73b
Revises: e65ebd0c08af
Create Date: 2026-08-27 21:09:31.175790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a6a8e36cf73b'
down_revision: Union[str, Sequence[str], None] = 'e65ebd0c08af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # shortform_sessions.last_recommendation의 코멘트 문구 drift는 이 변경과
    # 무관해 이 마이그레이션에서 뺐다 — 필요하면 별도로 반영한다.
    op.add_column('store_insights', sa.Column('insight_data', sa.JSON(), nullable=True, comment='구조화된 분석 데이터(나이·성별 분포 등, 유형마다 모양 다름)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_insights', 'insight_data')
    # ### end Alembic commands ###
