"""add recommendation_id to shorts_projects

Revision ID: a840dd2f99ad
Revises: 09e88d81b191
Create Date: 2026-08-24 20:26:22.721789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a840dd2f99ad'
down_revision: Union[str, Sequence[str], None] = '09e88d81b191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_shorts_projects', sa.Column('recommendation_id', sa.String(length=64), nullable=True, comment='R06 수락 시점의 AI 추천 ID(내부용, R14 연동 시 재사용)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shorts_projects', 'recommendation_id')
    # ### end Alembic commands ###
