"""add guide and draft columns

Revision ID: bbb10d72276d
Revises: c28606c07fd9
Create Date: 2026-08-23 21:38:29.412664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbb10d72276d'
down_revision: Union[str, Sequence[str], None] = 'c28606c07fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shooting_tasks', sa.Column('guide', sa.JSON(), nullable=True, comment='촬영 안내(guide_type/instructions/broll_shot)'))
    op.add_column('store_shorts_projects', sa.Column('current_step', sa.String(length=30), nullable=True, comment='진행 단계'))
    op.add_column('store_shorts_projects', sa.Column('client_state', sa.JSON(), nullable=True, comment='앱 복원용 상태'))
    op.add_column('store_shorts_projects', sa.Column('last_saved_at', sa.DateTime(), nullable=True, comment='마지막 임시저장 시각(UTC)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shorts_projects', 'last_saved_at')
    op.drop_column('store_shorts_projects', 'client_state')
    op.drop_column('store_shorts_projects', 'current_step')
    op.drop_column('shooting_tasks', 'guide')
    # ### end Alembic commands ###
