"""create shooting_tasks table

Revision ID: c28606c07fd9
Revises: 54f3cf0cc2e6
Create Date: 2026-08-23 20:59:11.270687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28606c07fd9'
down_revision: Union[str, Sequence[str], None] = '54f3cf0cc2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shooting_tasks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='태스크 ID'),
    sa.Column('shorts_project_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='숏폼 프로젝트 ID'),
    sa.Column('scene_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='연결된 콘티 장면 ID'),
    sa.Column('task_type', sa.String(length=50), nullable=True, comment='태스크 유형(영상촬영/대사/B-roll 등)'),
    sa.Column('task_title', sa.String(length=200), nullable=True, comment='태스크명'),
    sa.Column('task_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', 'RETAKE_NEEDED', name='taskstatus', native_enum=False, length=20), nullable=False, comment='진행 상태(완료/진행중/미완료/재촬영 필요)'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='태스크 보드 노출 순서'),
    sa.Column('footage_url', sa.String(length=255), nullable=True, comment='촬영본 파일 URL(재촬영 시 덮어씀, 테이크 이력 없음)'),
    sa.Column('footage_type', sa.Enum('VIDEO', 'IMAGE', 'AUDIO', name='footagetype', native_enum=False, length=10), nullable=True, comment='촬영본 파일 유형'),
    sa.Column('footage_duration_sec', sa.Integer(), nullable=True, comment='촬영본 길이(초)'),
    sa.Column('ai_eval_score', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='AI 평가 점수(현재 촬영본 기준, 참고값)'),
    sa.Column('ai_is_usable', sa.Boolean(), nullable=True, comment='현재 촬영본의 편집 사용 가능 여부'),
    sa.Column('ai_eval_issues', sa.Text(), nullable=True, comment='AI가 발견한 문제점/개선 제안'),
    sa.Column('ai_evaluated_at', sa.DateTime(), nullable=True, comment='AI 평가 수행 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='상태/촬영본 최종 변경일시(UTC)'),
    sa.ForeignKeyConstraint(['scene_id'], ['storyboard_scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shorts_project_id'], ['store_shorts_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shooting_tasks_shorts_project_id'), 'shooting_tasks', ['shorts_project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shooting_tasks_shorts_project_id'), table_name='shooting_tasks')
    op.drop_table('shooting_tasks')
    # ### end Alembic commands ###
