"""add project_title

Revision ID: caba912f8ced
Revises: d879c7d9231a
Create Date: 2026-08-24 11:16:23.306309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caba912f8ced'
down_revision: Union[str, Sequence[str], None] = 'd879c7d9231a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_shorts_projects', sa.Column('project_title', sa.String(length=200), nullable=True, comment='AI가 지은 프로젝트 제목 - 7.1 결과'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_shorts_projects', 'project_title')
    # ### end Alembic commands ###
