"""add push_notified_at to video_outputs

Revision ID: cf53ae305828
Revises: 59b5687bd2dc
Create Date: 2026-08-26 18:13:26.504771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cf53ae305828'
down_revision: Union[str, Sequence[str], None] = '59b5687bd2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_outputs', sa.Column('push_notified_at', sa.DateTime(), nullable=True, comment='편집 완료/실패 푸시 알림을 보낸 시각(UTC)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_outputs', 'push_notified_at')
    # ### end Alembic commands ###
