"""create sns_post_metrics table

Revision ID: d879c7d9231a
Revises: 548fc558f4ae
Create Date: 2026-08-24 02:24:28.778804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd879c7d9231a'
down_revision: Union[str, Sequence[str], None] = '548fc558f4ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sns_post_metrics',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='지표 ID'),
    sa.Column('sns_post_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='게시물 ID'),
    sa.Column('metric_name', sa.String(length=50), nullable=False, comment='지표명(views/likes/comments/shares/saves 등)'),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=2), nullable=True, comment='지표 값'),
    sa.Column('collected_at', sa.DateTime(), nullable=False, comment='수집 시각(UTC)'),
    sa.ForeignKeyConstraint(['sns_post_id'], ['sns_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sns_post_metrics_sns_post_id'), 'sns_post_metrics', ['sns_post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sns_post_metrics_sns_post_id'), table_name='sns_post_metrics')
    op.drop_table('sns_post_metrics')
    # ### end Alembic commands ###
