"""create store_photos table

Revision ID: dbd93a5b9f1d
Revises: fb6224d77363
Create Date: 2026-08-23 12:55:23.076701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd93a5b9f1d'
down_revision: Union[str, Sequence[str], None] = 'fb6224d77363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_photos',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='사진 ID'),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='가게 ID'),
    sa.Column('file_url', sa.String(length=255), nullable=False, comment='저장소 키(응답에서 전체 URL로 변환)'),
    sa.Column('category', sa.String(length=20), nullable=True, comment='사진 분류(간판/외관/내부/메뉴/제조·시술/인물/기타) - AI 자동분류 예정'),
    sa.Column('has_sensitive_info', sa.Boolean(), nullable=False, comment='고객 얼굴 등 민감정보 포함 여부(편집 시 사용 제한 판단)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='등록일시(UTC)'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_photos_store_id'), 'store_photos', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_photos_store_id'), table_name='store_photos')
    op.drop_table('store_photos')
    # ### end Alembic commands ###
