"""add render_stage, render_progress, error_message to video_outputs

Revision ID: e65ebd0c08af
Revises: cf53ae305828
Create Date: 2026-08-27 13:02:24.201619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e65ebd0c08af'
down_revision: Union[str, Sequence[str], None] = 'cf53ae305828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # shortform_sessions.last_recommendation의 코멘트 문구 drift는 이 변경과
    # 무관해 이 마이그레이션에서 뺐다 — 필요하면 별도로 반영한다.
    op.add_column('video_outputs', sa.Column('render_stage', sa.String(length=30), nullable=True, comment='AI 편집 단계(PREPARING_VIDEO_CONTEXT 등)'))
    op.add_column('video_outputs', sa.Column('render_progress', sa.Integer(), nullable=True, comment='AI가 보고하는 실제 진행률(0~100). 없으면 근사값 사용'))
    op.add_column('video_outputs', sa.Column('error_message', sa.Text(), nullable=True, comment='FAILED일 때 AI가 준 실패 사유 원문'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_outputs', 'error_message')
    op.drop_column('video_outputs', 'render_progress')
    op.drop_column('video_outputs', 'render_stage')
    # ### end Alembic commands ###
