"""create store_menus, store_target_customers, store_insights

Revision ID: fb6224d77363
Revises: 23fd8fdf7f13
Create Date: 2026-08-23 12:25:27.804810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6224d77363'
down_revision: Union[str, Sequence[str], None] = '23fd8fdf7f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_insights',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='인사이트 ID'),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='가게 ID'),
    sa.Column('insight_type', sa.String(length=30), nullable=True, comment='유형(상권분석/카드뉴스/다음숏폼추천 등)'),
    sa.Column('insight_title', sa.String(length=200), nullable=True, comment='제목'),
    sa.Column('insight_content', sa.Text(), nullable=True, comment='분석 내용'),
    sa.Column('insight_source', sa.String(length=50), nullable=True, comment='근거 출처(외부데이터/AI추론)'),
    sa.Column('generated_at', sa.DateTime(), nullable=False, comment='생성/갱신일시(UTC, 데이터 신선도 판단에 사용)'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_insights_generated_at'), 'store_insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_store_insights_store_id'), 'store_insights', ['store_id'], unique=False)
    op.create_table('store_menus',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='메뉴 ID'),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='가게 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='메뉴명'),
    sa.Column('price', sa.Integer(), nullable=True, comment='가격'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('image_url', sa.String(length=255), nullable=True, comment='메뉴 이미지 URL'),
    sa.Column('is_new_menu', sa.Boolean(), nullable=False, comment='신메뉴 여부(추천 우선순위에 사용)'),
    sa.Column('is_event_menu', sa.Boolean(), nullable=False, comment='이벤트 메뉴 여부'),
    sa.Column('is_sold_out', sa.Boolean(), nullable=False, comment='품절 여부(홍보 소재 제외 판단에 사용)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_menus_store_id'), 'store_menus', ['store_id'], unique=False)
    op.create_table('store_target_customers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='타깃 ID'),
    sa.Column('store_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='가게 ID'),
    sa.Column('target_type', sa.String(length=20), nullable=True, comment='타깃 유형(주/보조/성장)'),
    sa.Column('target_description', sa.Text(), nullable=True, comment='타깃 설명(생활맥락/구매동기 등)'),
    sa.Column('ai_confidence', sa.String(length=20), nullable=True, comment='AI 추론 신뢰도'),
    sa.Column('status', sa.Enum('SUGGESTED', 'CONFIRMED', 'HIDDEN', name='targetstatus', native_enum=False, length=20), nullable=False, comment='확인 상태(AI제안/사장님확정/숨김)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시(UTC)'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시(UTC)'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_target_customers_store_id'), 'store_target_customers', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_target_customers_store_id'), table_name='store_target_customers')
    op.drop_table('store_target_customers')
    op.drop_index(op.f('ix_store_menus_store_id'), table_name='store_menus')
    op.drop_table('store_menus')
    op.drop_index(op.f('ix_store_insights_store_id'), table_name='store_insights')
    op.drop_index(op.f('ix_store_insights_generated_at'), table_name='store_insights')
    op.drop_table('store_insights')
    # ### end Alembic commands ###
